-- Nibras database source of truth
--
-- Do not use this file as a deployment script. The schema is maintained as ordered,
-- reviewable migrations under ./migrations so security fixes cannot drift from a
-- duplicated snapshot.
--
-- Existing project:
--   supabase migration up
--
-- Fresh project:
--   apply every SQL file in supabase/migrations in filename order, then add the
--   initial developer/admin email directly to private.admin_allowlist from the
--   Supabase SQL editor. Do not commit privileged account addresses or credentials.
--
-- Required security invariants enforced by the migrations:
--   * RLS on every public user-data table
--   * authenticated ownership policies
--   * private admin allowlist and admin helper
--   * protected profile role/email fields
--   * authenticated AI usage logs
--   * atomic ai_burst and ai_daily rate limits
--   * mandatory policy-consent fields
--   * rate-limited client error logging
